/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#5d3fd3",
        "primary-dim": "#5130c6",
        "primary-container": "#a391ff",
        secondary: "#0050d4",
        "secondary-dim": "#0046bb",
        "secondary-container": "#c4d0ff",
        tertiary: "#535b71",
        "tertiary-container": "#dae2fd",
        surface: "#f5f7f9",
        "surface-dim": "#d0d5d8",
        "surface-bright": "#f5f7f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eef1f3",
        "surface-container": "#e5e9eb",
        "surface-container-high": "#dfe3e6",
        "surface-container-highest": "#d9dde0",
        "on-surface": "#2c2f31",
        "on-surface-variant": "#595c5e",
        outline: "#747779",
        "outline-variant": "#abadaf",
        background: "#f5f7f9",
        success: "#10B981",
        warning: "#F59E0B",
        danger: "#EF4444",
      },
    },
  },
  plugins: [],
};
